config/routes.rb
Shortenizer::Engine.routes.draw do
  root 'u#new'

  match '/show', to: 'u#show', via: :get
  match '/shorten', to: 'u#new', via: :get, as: :new_short_link
  match '/create', to: 'u#create', via: :post, as: :create_short_link
  match '/:shortlink', to: 'u#index', via: :get
end

app/models/shortenizer/url.rb
module Shortenizer
  class Url < ActiveRecord::Base

    before_create :create_unique_identifier
    before_create :append_https

    def create_unique_identifier
      begin
        self.shortlink = SecureRandom.hex(8)
      end while self.class.exists?(:shortlink => shortlink)
    end

    def append_https
      unless self.target =~ /http/i
        self.target = "http://#{self.target}"
      end
    end
  end
end

app/controllers/shortenizer/application_controller.rb
module Shortenizer
  class ApplicationController < ActionController::Base
  end
end

app/controllers/shortenizer/u_controller.rb
module Shortenizer
  class UController < ApplicationController

    def index
      target = Url.find_by(shortlink: params[:shortlink]).target
      redirect_to target
    end

    def new
      @url = Shortenizer::Url.new
    end

    def create
      @url = Shortenizer::Url.new(url_params)

      if @url.save
        flash[:message] = "Your URL has been shortened..."
      else
        flash[:message] = "Error occured, please try again!"
      end

      redirect_to action: :show, shortlink: @url.shortlink
    end

    def show
      url_obj = Url.find_by(shortlink: params[:shortlink])
      @url = Shortenizer::UrlPresenter.new(url_obj, request)
    end

    private
    def url_params
      params.require(:url).permit(:target, :shortlink)
    end

  end
end

app/helpers/shortenizer/application_helper.rb
module Shortenizer
  module ApplicationHelper
  end
end

app/views/layouts/shortenizer/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortenizer</title>
  <%= stylesheet_link_tag    "shortenizer/application", media: "all" %>
  <%= javascript_include_tag "shortenizer/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='shortenizer wrapper'>
    <div class='shortenizer flash-message'>
      <%= flash[:message] if flash[:message] %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/shortenizer/u/new.html.erb
<%= form_for :url, url: create_short_link_path, html: { class: 'shortenizer form' } do |f| %>
  <%= f.text_field :target, placeholder: 'Paste a link to shorten it...' %>
  <%= f.submit "Shorten", class: 'btn-shorten' %>
<% end %>

app/views/shortenizer/u/show.html.erb
<%= form_for :url, html: { class: 'shortenizer form' } do |f| %>
  <%= f.text_field :target, value: @url.full_url %>
  <%= link_to "Copy", '', class: 'btn-copy', id: 'btn-copy', data: { "clipboard-text" => @url.full_url }, onClick: 'return false' %>
  <%= link_to "New", new_short_link_path, class: 'btn-new' %>
<% end %>